spring:
  datasource:
    url: jdbc:h2:tcp://example.com
    driver-class-name: org.h2.Driver
    username: example

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: example
      port: ---

jwt:
  secretKey: ---

  access:
    expiration: ---
    header: AccessToken

  refresh:
    expiration: ---
    header: RefreshToken

r2:
  account-id: ----
  access-key: ----
  secret-key: ----
  bucket: bucketName